#!/bin/sh
set -x
set -e
# export MAKEOBJDIR=/usr/obj/$(pwd -P)

setup_script () {
    printf "Running setup_script\n"

    uname -a
    gpart show
    df -m
    pkg --version
    pw useradd -n user -m
    mkdir -p /usr/obj/$(pwd -P)
    chown user:user /usr/obj/$(pwd -P)
    su user -c "git config --global --add safe.directory $(pwd -P)"
}

build_world_script () {
    printf "Running build_world_script\n"
    set +e
    su user -c "make -j$(nproc) ${EXTRA_MAKE_FLAGS} \
    CROSS_TOOLCHAIN=${TOOLCHAIN} \
    WITHOUT_TOOLCHAIN=yes buildworld"
    set -e
}

build_kernel_script () {
    printf "Running build_kernel_script\n"

    su user -c "make -j$(nproc) \
    CROSS_TOOLCHAIN=${TOOLCHAIN} WITHOUT_TOOLCHAIN=yes \
    buildkernel"
}

package_script () {
    printf "Running package_script\n"

    su user -c "make -j$(nproc) CROSS_TOOLCHAIN=${TOOLCHAIN} WITHOUT_TOOLCHAIN=yes packages"
}

package_check_script () {
    printf "Running package_check_script\n"

    su user -c "/usr/libexec/flua \
    tools/pkgbase/metalog_reader.lua \
    -c /usr/obj/$(pwd -P)/${TARGET}.${TARGET_ARCH}/worldstage/METALOG"
}

test_script () {
    printf "Running test_script\n"

    sh .cirrus-ci/pkg-install.sh qemu-nox11
    sh tools/boot/ci-qemu-test.sh
}

make_sysent_script () {
    printf "Running make_sysent_script\n"
    # Check that make sysent results were committed if required
    make sysent
    if ! git diff --exit-code; then printf "\n>>> Generated \
    sysent files not updated, run make sysent <<<\n"; false; fi
}

include_ldirs_script () {
    printf "Running include_ldirs_script\n"
    # Check that includes/Makefile refers to existing directories
    if ! make -C include/ check-ldirs; then printf "\n>>> include/Makefile lists nonexistant directories <<<\n"; false; fi
}

makeman_script () {
    printf "Running makeman_script\n"
    # Check that the committed src.conf.5 matches the one generated by
    # tools/build/options/makeman (modulo the date which always updates)
    # XXX: This script is slow so keep it last
    (make makeman 2> /tmp/makeman.out); cat /tmp/makeman.out
    if ! git diff --exit-code --ignore-matching-lines "^.Dd" share/man/man5/src.conf.5; then printf "\n>>> src.conf.5 was not updated as required <<<\n"; false; fi
    if grep -q "no description found" /tmp/makeman.out; then printf "\n>>> Missing description files <<<\n"; false; fi
}

post_script () {
    printf "Running post_script\n"

    df -m
    du -m -s /usr/obj
}

all () {
    printf "Running all scripts\n"

    setup_script
    build_world_script
    build_kernel_script
    package_script
    package_check_script
    test_script
    make_sysent_script
    include_ldirs_script
    makeman_script
    post_script
}

# Handle CLI arguments
for arg in "$@"; do
    case "$arg" in
        --setup_script)
            setup_script
            ;;
        --build_world_script)
            build_world_script
            ;;
        --build_kernel_script)
            build_kernel_script
            ;;
        --package_script)
            package_script
            ;;
        --package_check_script)
            package_check_script
            ;;
        --test_script)
            test_script
            ;;
        --make_sysent_script)
            make_sysent_script
            ;;
        --include_ldirs_script)
            include_ldirs_script
            ;;
        --makeman_script)
            makeman_script
            ;;
        --post_script)
            post_script
            ;;
        --all)
            all
            ;;
        --help|-h)
            echo "Usage: $0 [SCRIPT]"
            echo ""
            echo "Options:"
            echo "  --setup_script            "
            echo "  --build_world_script      "
            echo "  --build_kernel_script     "
            echo "  --package_script          "
            echo "  --package_check_script    "
            echo "  --test_script             "
            echo "  --make_sysent_script      "
            echo "  --include_ldirs_script    "
            echo "  --makeman_script          "
            echo "  --post_script             "
            echo "  --all         runs all above tasks in order given"
            echo "Note: At least one feature must be specified."
            exit 0
            ;;
        *)
            echo "Warning: Unknown argument '$arg' ignored." >&2
            ;;
    esac
done
